### ISSUE TITLE
Author should be able to display stored Word Documents

### ISSUE THREAD

**Issue by trystant** [campgurus/writersapp#1]
We want the author to be able to see the contents of uploaded Word documents. The current thought is to use the [docx](https://github.com/chrahunt/docx) gem to parse & display those contents.

**Comment by trystant** [comment]
After confirming that the docx gem works as expected, the next steps are to open the doc with the [carrierwave](https://github.com/carrierwaveuploader/carrierwave) gem's `url` property and display the contents on the page.

**Comment by campgurus** [comment]
this is complete.
